name: biore
favicon: null
layout_spectrum: 0.89873
typography_spectrum: 0.30764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050409'
    - '#edd2c7'
    - '#503b38'
    - '#c79a7b'
    - '#628312'
  brandStrength: 0.1875
  lightness: 0.6633293724153191
  saturation: 0.7621878338977695
  rhythmicContrast: 0.43637368245981634
purpose: []
